export const SEND_REGISTRATION_DATA = 'REGISTRATION/SEND_REGISTRATION_DATA';
export const START_REGISTRATION_REQUEST = 'REGISTRATION/START_REGISTRATION_REQUEST';
export const STOP_REGISTRATION_REQUEST = 'REGISTRATION/STOP_REGISTRATION_REQUEST';
