const types = {
	SELECT_IMAGE: 'DASHBOARD/SELECT_IMAGE',
	SET_ACTIVE_IMAGES_STATUS: 'SET_ACTIVE_IMAGES_STATUS',
	UPDATE_ACTIVE_IMAGES_STATUS: 'UPDATE_ACTIVE_IMAGES_STATUS',
	UPDATE_TEXT_FILTER: 'DASHBOARD/UPDATE_TEXT_FILTER',
};

export default types;
