export default {
	CHANGE_CURRENT_STEP: 'IMAGE_CREATION/CHANGE_CURRENT_STEP',
	SELECT_ENTITY: 'IMAGE_CREATION/SELECT_ENTITY',
	SET_FILTER_BY_TYPE: 'IMAGE_CREATION/SET_FILTER_BY_TYPE',
	CHANGE_INITIALIZATION_SLIDE: 'IMAGE_CREATION/CHANGE_INITIALIZATION_SLIDE',
};
