import styleColors from '!sass-variable-loader!styles/colors.scss';

export const enum entitiesActionTypes {
	REQUEST_IMAGES = '@@ENTITIES/REQUEST_IMAGES',
	UPDATE_IMAGE = '@@ENTITIES/UPDATE_IMAGE',
	REQUEST_IMAGES_SUCCESS = '@@ENTITIES/REQUEST_IMAGES_SUCCESS',
	UPDATE_IMAGES_START_DATE = '@@ENTITIES/UPDATE_IMAGES_START_DATE',
	REQUEST_IMAGES_ERROR = '@@ENTITIES/REQUEST_IMAGES_ERROR',
}

export const COLORS = styleColors;

