const types = {
  REQUEST_LOUNCHES: 'ENTITIES/REQUEST_LOUNCHES',
  REQUEST_LOUNCHES_SUCCESS: 'ENTITIES/REQUEST_LOUNCHES_SUCCESS',
  REQUEST_LOUNCHES_ERROR: 'ENTITIES/REQUEST_LOUNCHES_ERROR'
}

export default types