const types = {
  REQUEST_IMAGES: 'ENTITIES/REQUEST_IMAGES',
  REQUEST_IMAGES_SUCCESS: 'ENTITIES/REQUEST_IMAGES_SUCCESS',
  REQUEST_IMAGES_ERROR: 'ENTITIES/REQUEST_IMAGES_ERROR'
}

export default types