export const LOGIN = 'USER/LOGIN';
export const LOGOUT = 'USER/LOGOUT';
export const SET_USER_DATA = 'USER/SET_USER_DATA';
export const CHECK_USER_LOGGED = 'USER/CHECK_USER_LOGGED';
export const SET_USER_ACCESS_TOKEN = 'USER/SET_USER_ACCESS_TOKEN';
export const SET_USER_REFRESH_TOKEN = 'USER/SET_USER_REFRESH_TOKEN';
