export const CREATE_IMAGE_CHANGE_CURRENT_STEP = 'CREATE_IMAGE/CHANGE_CURRENT_STEP';
export const CREATE_IMAGE_SELECT_ENTITY = 'CREATE_IMAGE/CREATE_IMAGE_SELECT_ENTITY';
export const CREATE_IMAGE_SET_FILTER_BY_TYPE = 'CREATE_IMAGE/CREATE_IMAGE_SET_FILTER_BY_TYPE';
export const CREATE_IMAGE_CHANGE_INITIALIZATION_SLIDE = 'CREATE_IMAGE/CREATE_IMAGE_CHANGE_INITIALIZATION_SLIDE';
