export const enum authActionTypes {
	SEND_AUTH_DATA = '@@AUTH/SEND_AUTH_DATA',
	START_AUTH_REQUEST = '@@AUTH/START_AUTH_REQUEST',
	STOP_AUTH_REQUEST = '@@AUTH/STOP_AUTH_REQUEST',
	CHANGE_LOGIN_ERROR = '@@AUTH/CHANGE_LOGIN_ERROR',
}
