export const SEND_AUTH_DATA = 'AUTH/SEND_AUTH_DATA';
export const START_AUTH_REQUEST = 'AUTH/START_AUTH_REQUEST';
export const STOP_AUTH_REQUEST = 'AUTH/STOP_AUTH_REQUEST';
export const CHANGE_LOGIN_ERROR = 'AUTH/CHANGE_LOGIN_ERROR';
